<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Helpers compartidos del conector NewBytes.
 *
 * - Detección segura de FIFU (funciona también en contexto WP-Cron).
 * - Lock de concurrencia de sincronización.
 * - Directorio de logs fuera del webroot.
 *
 * @see .spec/specs/SPEC-0005-cron-is-plugin-active.md
 * @see .spec/specs/SPEC-0007-sync-concurrency-lock.md
 * @see .spec/specs/SPEC-0012-logging-hardening.md
 */

if (!defined('NB_SYNC_LOCK')) {
    define('NB_SYNC_LOCK', 'nb_sync_running');
}

/* -------------------------------------------------------------------------
 * FIFU (Featured Image From URL)
 * ---------------------------------------------------------------------- */

/**
 * ¿Está activo FIFU (gratuito o premium)?
 *
 * is_plugin_active() vive en wp-admin/includes/plugin.php, que NO se carga en
 * WP-Cron. Lo requerimos on-demand para no provocar un fatal en la sync
 * automática.
 */
function nb_is_fifu_active()
{
    if (!function_exists('is_plugin_active')) {
        require_once ABSPATH . 'wp-admin/includes/plugin.php';
    }

    return is_plugin_active('featured-image-from-url/featured-image-from-url.php')
        || is_plugin_active('fifu-premium/fifu-premium.php');
}

/**
 * Asigna la imagen destacada del producto vía FIFU, si corresponde.
 *
 * No-op silencioso si FIFU no está activo, la función no existe o no hay imagen.
 *
 * @param int   $product_id ID del producto de WooCommerce.
 * @param array $row         Fila de producto de la API NewBytes.
 */
function nb_set_fifu_image($product_id, array $row)
{
    $product_id = (int) $product_id;

    if ($product_id <= 0 || !nb_is_fifu_active() || !function_exists('fifu_dev_set_image')) {
        return;
    }

    $image = !empty($row['mainImageExp'])
        ? $row['mainImageExp']
        : (!empty($row['mainImage']) ? $row['mainImage'] : '');

    if ($image !== '') {
        fifu_dev_set_image($product_id, $image);
    }
}

/**
 * Trae la descripción autogenerada de un producto desde la API NewBytes.
 *
 * @param int    $nb_id ID interno NewBytes del producto.
 * @param string $token Bearer token válido.
 * @return string|null Descripción, o null ante cualquier problema.
 */
function nb_fetch_product_description($nb_id, $token)
{
    $nb_id = (int) $nb_id;
    if ($nb_id <= 0 || empty($token)) {
        return null;
    }

    $response = wp_remote_get(API_URL_NB . '/autoGeneratedDescription/' . $nb_id, array(
        'headers'  => array(
            'Authorization' => 'Bearer ' . $token,
            'Content-Type'  => 'application/json',
        ),
        'timeout'  => 60,
        'blocking' => true,
    ));

    if (is_wp_error($response) || (int) wp_remote_retrieve_response_code($response) !== 200) {
        return null;
    }

    $data = json_decode(wp_remote_retrieve_body($response), true);
    if (json_last_error() !== JSON_ERROR_NONE || !isset($data['description'])) {
        return null;
    }

    return (string) $data['description'];
}

/* -------------------------------------------------------------------------
 * Lock de concurrencia de sincronización
 * ---------------------------------------------------------------------- */

/**
 * Intenta tomar el lock de sincronización.
 *
 * @param int $ttl Segundos de vida del lock (fallback si el proceso muere).
 * @return bool True si se tomó; false si ya había una sync en curso.
 */
function nb_sync_acquire_lock($ttl = 1800)
{
    if (get_transient(NB_SYNC_LOCK)) {
        return false;
    }

    set_transient(NB_SYNC_LOCK, time(), (int) $ttl);

    return true;
}

/**
 * Renueva el TTL del lock (para procesos largos por lotes).
 */
function nb_sync_refresh_lock($ttl = 1800)
{
    set_transient(NB_SYNC_LOCK, time(), (int) $ttl);
}

/**
 * Libera el lock de sincronización.
 */
function nb_sync_release_lock()
{
    delete_transient(NB_SYNC_LOCK);
}

/**
 * ¿Hay una sincronización en curso?
 */
function nb_sync_is_locked()
{
    return (bool) get_transient(NB_SYNC_LOCK);
}

/* -------------------------------------------------------------------------
 * Directorio de logs (fuera del webroot, protegido)
 * ---------------------------------------------------------------------- */

/**
 * Devuelve (creándolo si hace falta) el directorio de logs del plugin dentro de
 * wp-content/uploads/nb-logs/, con index.php y .htaccess de protección.
 *
 * @return string Ruta con barra final.
 */
function nb_log_dir()
{
    $upload = wp_upload_dir();
    $dir    = trailingslashit($upload['basedir']) . 'nb-logs/';

    if (!is_dir($dir)) {
        wp_mkdir_p($dir);
    }

    if (is_dir($dir) && is_writable($dir)) {
        $index = $dir . 'index.php';
        if (!file_exists($index)) {
            @file_put_contents($index, "<?php\n// Silence is golden.\n");
        }
        $htaccess = $dir . '.htaccess';
        if (!file_exists($htaccess)) {
            @file_put_contents($htaccess, "Deny from all\n");
        }
    }

    return $dir;
}
